CODEOWNERS
MAINTAINERS.md

Add helpers for maintenance

---

besu.rb

Release Hypereledger Besu 1.3.0

---

besu.rb

updating to 1.3.3

---

besu.rb

Signed-off-by: Joshua Fernandes <joshua.fernandes@consensys.net>

updating to 1.4.0

---

besu.rb

Besu 1.5.1

---

besu.rb

Besu 1.5.2

---

besu.rb

Update to 1.5.3

---

besu.rb

Update to 20.10.0

---

besu.rb
updateBesu.sh

Fix Dependencies

---

besu.rb

Signed-off-by: David Mechler <david.mechler@consensys.net>

Update homebrew to 20.10.4

---

besu.rb

release 21.1.0

---

updateBesu.sh

Signed-off-by: Karim TAAM <t2am.karim@gmail.com>

Replace bintray url and use artifactory

---

besu.rb

Update to 21.1.3

---

besu.rb

Update to 21.1.5

---

besu.rb

Update to 21.1.7

---

besu.rb

Release 21.7.1

---

MAINTAINERS.md
README.md

Update links to main branch for doc links.

CI Changes for `main` branch migration

---

besu.rb

release 21.7.2

---

besu.rb

updating formula to new release

---

besu.rb

update homebrew-besu version to 21.7.4

21.7.4 release

---

README.md
besu.rb

Update to 21.10.0-RC2

---

besu.rb

21.10.0 quarterly release

---

besu.rb

Release 21.10.2

---

besu.rb

Update to 21.10.3

---

besu.rb

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

Update to 21.10.5

---

besu.rb

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

Update to 21.10.6

---

besu.rb

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

Update to 21.10.7

---

besu.rb

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

Update to 21.10.8

---

besu.rb

Release 22.1.0

---

besu.rb

Release 22.1.1

---

besu.rb

Signed-off-by: Frank Li <b439988l@gmail.com>

Release 22.1.2

---

besu.rb

updated for besu 22.4.1 release

updated for besu 22.4.1

---

besu.rb

Signed-off-by: garyschulte <garyschulte@gmail.com>

release 22.4.4

---

besu.rb

Release 22.7.0

---

besu.rb

Signed-off-by: Justin Florentine <justin+github@florentine.us>

update version to 22.7.1

---

besu.rb

22.7.2 release

---

besu.rb

Signed-off-by: garyschulte <garyschulte@gmail.com>

22.7.3 release

---

besu.rb

Signed-off-by: Justin Florentine <justin+github@florentine.us>

release version

---

besu.rb

Signed-off-by: Justin Florentine <justin+github@florentine.us>

uprev version to 22.7.5

---

besu.rb

update homebrew to latest stable release version 22.7.6

update to 22.7.6

---

besu.rb

Signed-off-by: Fabio Di Fabio <fabio.difabio@consensys.net>

Update to 22.7.7

---

besu.rb

Signed-off-by: Fabio Di Fabio <fabio.difabio@consensys.net>

Release 22.10.0

---

besu.rb

release 22.10.1

---

besu.rb

release 22.10.2

---

besu.rb

release 22.10.3

---

besu.rb

23.1.0 release

---

besu.rb

Update homebrew for besu 23.1.1

release 23.1.1 for Goerli Shapella

---

besu.rb

update homebrew-besu to 23.1.2

23.1.2 release

---

besu.rb

release 23.1.3

---

besu.rb

Update the version of Besu to 23.4.4

update to 23.4.4

---

besu.rb

release for 23.7.1

---

besu.rb

Republish of 23.7.1

---

besu.rb

Update besu homebrew to 23.7.2

---

besu.rb

Add evmtool to the homebrew deploy

Add evmtool

---

besu.rb
updateBesu.sh

Also made 11 -> 17 and evmtool changes permanent

Release 23.7.3

---

besu.rb

Signed-off-by: Simon Dudley <simon.dudley@consensys.net>

Update 23.10.1 SHA since the CI build accidentally reran and overwrote it

---

besu.rb

https://github.com/hyperledger/besu/releases/tag/24.1.2

Release 24.1.2

---

besu.rb

New release, sourced from github packages.

release 24.3.0

---

besu.rb

release 24.3.3

---

besu.rb

release 24.6.0
